spring.application.name=nb3tx
server.servlet.context-path=/nb3tx
server.port=9080
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

spring.datasource.url=jdbc:postgresql://localhost:5432/nb3txdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false



remote.central.fx-n510-url=http://localhost:5017/central/api/fx/n510
remote.central.tw-n920-url=http://localhost:5017/central/api/tw/n920
remote.central.tw-n110-url=http://localhost:5017/central/api/tw/n110
remote.central.fx-f574-url=http://localhost:5017/central/api/fx/f574
remote.central.fx-f007-url=http://localhost:5017/central/api/fx/f007

remote.central.tw-n920-url=http://localhost:5017/central/api/tw/n920
remote.central.tw-n921-url=http://localhost:5017/central/api/tw/n921
remote.central.tw-n110-url=http://localhost:5017/central/api/tw/n110
remote.central.tw-n070-url=http://localhost:5017/central/api/tw/n070

remote.api.central-url=http://localhost:5017/central/api/tx/

